# -*- coding: utf-8 -*-
"""del_lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vg9F68xR2fRrI9KQQPvQVbfJU87IT72O
"""

import tensorflow as tf
import pandas as pd
from tensorflow.keras import layers
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# load data
data = load_iris()
df = pd.DataFrame(data.data)

size = int(0.75*len(df))
x_train = df.iloc[: size, :-1]
y_train = df.iloc[: size, -1]
x_test = df.iloc[size: , :-1]
y_test = df.iloc[size: , -1]

# Convert data to TensorFlow tensors
x_train = tf.convert_to_tensor(x_train)
y_train = tf.convert_to_tensor(y_train)
x_test = tf.convert_to_tensor(x_test)
y_test = tf.convert_to_tensor(y_test)

dropout_rate = 0.2
model = tf.keras.Sequential([
        layers.Dense(4, activation='relu'),
        layers.Dropout(dropout_rate),
        layers.Dense(10, activation='relu'),
        layers.Dense(10, activation='softmax')
    ])

model.summary()

model.compile(optimizer='SGD', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
d = model.fit(x_train, y_train, epochs=10, validation_data = (x_test, y_test))

model.get_weights()

test_score, test_accuracy = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_accuracy} %")